### ISSUE TITLE
Validation failed in file StreamingJsonDecoder.kt

### ISSUE THREAD

**Issue by Queatz** [hfhbd/routing-compose#231]
I am getting this error when including the dependency.

```
> Task :compileDevelopmentExecutableKotlinJs FAILED
e: java.lang.IllegalStateException: Validation failed in file StreamingJsonDecoder.kt
	at org.jetbrains.kotlin.backend.common.IrValidator.error(IrValidator.kt:86)
	at org.jetbrains.kotlin.backend.common.IrValidator.access$error(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator$elementChecker$1.invoke(IrValidator.kt:90)
	at org.jetbrains.kotlin.backend.common.IrValidator$elementChecker$1.invoke(IrValidator.kt:90)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.ensureBound(CheckIrElementVisitor.kt:61)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitDeclarationReference(CheckIrElementVisitor.kt:302)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitMemberAccess(IrElementVisitorVoid.kt:170)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitMemberAccess(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:173)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitFunctionAccess(CheckIrElementVisitor.kt:319)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructorCall(IrElementVisitorVoid.kt:179)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitConstructorCall(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructorCall(IrElementVisitorVoid.kt:180)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitConstructorCall(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitConstructorCall(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:20)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:93)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclarationReference(IrElementVisitorVoid.kt:140)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclarationReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitMemberAccess(IrElementVisitorVoid.kt:170)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitMemberAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:173)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructorCall(IrElementVisitorVoid.kt:179)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitConstructorCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitConstructorCall(IrElementVisitorVoid.kt:180)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitConstructorCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitConstructorCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:20)
	at org.jetbrains.kotlin.ir.expressions.IrThrow.acceptChildren(IrThrow.kt:18)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitThrow(IrElementVisitorVoid.kt:258)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitThrow(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitThrow(IrElementVisitorVoid.kt:259)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitThrow(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitThrow(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrThrow.accept(IrThrow.kt:15)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.acceptChildren(IrContainerExpression.kt:20)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitContainerExpression(IrElementVisitorVoid.kt:128)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitContainerExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:134)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:135)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:15)
	at org.jetbrains.kotlin.ir.expressions.IrCatch.acceptChildren(IrCatch.kt:22)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCatch(IrElementVisitorVoid.kt:243)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCatch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCatch(IrElementVisitorVoid.kt:244)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCatch(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCatch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrCatch.accept(IrCatch.kt:18)
	at org.jetbrains.kotlin.ir.expressions.IrTry.acceptChildren(IrTry.kt:23)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitTry(IrElementVisitorVoid.kt:240)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTry(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitTry(IrElementVisitorVoid.kt:241)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTry(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTry(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrTry.accept(IrTry.kt:19)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.acceptChildren(IrBlockBody.kt:20)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBody(IrElementVisitorVoid.kt:86)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:92)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:93)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:17)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclaration(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:49)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:52)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:53)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
	at org.jetbrains.kotlin.ir.declarations.IrClass.acceptChildren(IrClass.kt:50)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:40)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclaration(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:43)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitClass(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitClass(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitClass(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:46)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitPackageFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:71)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:22)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.acceptChildren(IrModuleFragment.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:30)
	at org.jetbrains.kotlin.backend.common.phaser.DumperVerifierKt.validationCallback(DumperVerifier.kt:142)
	at org.jetbrains.kotlin.backend.common.phaser.DumperVerifierKt.validationCallback$default(DumperVerifier.kt:134)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$validateIrBeforeLowering$1.invoke(JsLoweringPhases.kt:121)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$validateIrBeforeLowering$1.invoke(JsLoweringPhases.kt:120)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:61)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:53)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.ir.backend.js.CompilerWithICKt.lowerPreservingTags(compilerWithIC.kt:115)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compileIr(compiler.kt:152)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:68)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:49)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:392)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDevelopmentExecutableKotlinJs'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details
```

`gradle.properties`
```
kotlin.code.style=official
kotlin.native.enableDependencyPropagation=false
kotlin.js.webpack.major.version=4
kotlin.js.webpack.port=4040
kotlin.version=1.7.10
agp.version=4.2.2
compose.version=1.2.0-alpha01-dev770
```

**Comment by hfhbd** [comment]
Which version do you use of `routing-compose`? And could you try to use webpack 5, just remove the gradle property.

**Comment by Queatz** [comment]
> Which version do you use of `routing-compose`? And could you try to use webpack 5, just remove the gradle property.

I'm using `0.2.8`

I narrowed `gradle.properties` down to
```
kotlin.code.style=official
kotlin.version=1.7.10
agp.version=4.2.2
compose.version=1.2.0-alpha01-dev770

```
and still see this error

**Comment by hfhbd** [comment]
Hm, could you upload your project? Or share it privately?

**Comment by Queatz** [comment]
@hfhbd I pushed the code here https://github.com/Queatz/ailaai-web

Just uncomment the dependency and try to build

**Comment by hfhbd** [comment]
Thanks. It is a Kotlin IR bug. `routing-compose` uses `app.softwork:kotlinx-uuid-core` which depends on kotlinx.serialization.
The current version of routing (0.2.8) uses uuid (0.0.16) which uses serialization (1.4.0). But Ktor 2.1.0 uses serialization 1.3.3, which is unexpectly not compatible.

Workaround for this isse: use routing compose 0.2.7, which uses uuid 0.0.15 and depends on serialization 1.3.3, same as Ktor.

And btw: `kotlin("plugin.serialization") version "1.4.0"` should match the kotlin version `1.7.10`, but this does not effect this issue :)

**Comment by Queatz** [comment]
Thanks, yeah looks like `0.2.7` is working 👍🏼 will close the issue

**Comment by Queatz** [comment]
@hfhbd I pushed a commit to that repo.  Is it a bug that I can't navigate to `http://localhost:4040/card/50500361` directly, but if I start from a `noMatch` route like `http://localhost:4040/something` and click the button to go to `http://localhost:4040/card/50500361` it works?

**Comment by hfhbd** [comment]
You have to add a slash to your js location:
```
<script src="/ailaai.js"></script>
```

**Comment by Queatz** [comment]
Ahh, okay it works, thank you, sorry I'm new to Compose web 😄

**Comment by hfhbd** [comment]
You are welcome, yeah javascript is sometimes confusing.
