### ISSUE TITLE
Can't run compileDevelopmentExecutableKotlinJs

### ISSUE THREAD

**Issue by Altantur** [hfhbd/routing-compose#282]
Hello, I'm having following error when running dev server with Kotlin `1.8.20`, compose `1.4.0-rc03`:
```
Task ':webApp:compileDevelopmentExecutableKotlinJs' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':webApp:compileDevelopmentExecutableKotlinJs'.
Using Kotlin/JS IR backend
i: found daemon on port 17954 (25106676 ms old), trying to connect
i: connected to the daemon
e: java.lang.IllegalStateException: Symbol for kotlinx.serialization.modules/SerializersModuleCollector.polymorphicDefaultDeserializer|-5554727982800535415[0] is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:52)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.collectImplementedSymbol(CacheUpdater.kt:299)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.getExportedSignaturesAndAddMetadata-gNUL48g(CacheUpdater.kt:351)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.rebuildDirtySourceMetadata(CacheUpdater.kt:403)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCachesImpl(CacheUpdater.kt:704)
        at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCaches(CacheUpdater.kt:738)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:300)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```
Sorry for putting putting whole error. I'm using latest version 0.2.12.

**Comment by hfhbd** [comment]
Could you provide the whole build.gradle file? In general, this is a klib incompatible error. This format isn't stable yet and you still need to update all dependencies with a new Kotlin update.
At the moment, routing-compose does not use kotlinx-serialization, so you have to update another dependency using this library.

**Comment by Altantur** [comment]
Wow, thanks for the fast reply! Here is my build.gradle:
```
import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
}

group "com.example"
version "1.0-SNAPSHOT"

repositories {
    google()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

kotlin {
    js(IR) {
        browser {
            testTask {
                testLogging.showStandardStreams = true
                useKarma {
                    useChromeHeadless()
                    useFirefox()
                }
            }
        }
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation("app.softwork:routing-compose:0.2.12")
                implementation(project(":shared"))
                implementation(compose.html.core)
                implementation(compose.runtime)
            }
        }
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
    }
}
```

**Comment by hfhbd** [comment]
What's the dependencies of `shared`?

**Comment by Altantur** [comment]
Hey, thanks for the help! Updating libraries that are used in shared worked great.
